### ISSUE TITLE
Getting GCC compile error for installation on MacOS

### ISSUE THREAD

**Issue by MohitMayankOP** [phurwicz/hover#22]
I am trying to install `hover` on my MacOS Monterey which has the `miniforge` python installation (python 3.8). I get following error message --  `distutils.errors.CompileError: command 'gcc' failed with exit status 1`

Maybe a conda package will help with this?

**Comment by phurwicz** [comment]
Looking into it. Will do this:
- (optional) repro the error on Monterey
- create a conda package for the latest release version (0.5.0)

**Comment by phurwicz** [comment]
Update: this conda-forge PR for 0.5.0 is unlikely to pass due to failed builds. Here's what we have to do:

- **1** move `snorkel` to an optional dependency that is only required when you use rule-based features of hover (upcoming).
- **2** loose other dependency version specifications as much as we can.

Because **1** alters the source code, it makes more sense to start conda support at the upcoming 0.6.0 release.

@MohitMayankOP could you try a `pip` installation for 0.5.0 instead? Or `conda install -c phurwicz hover`.

**Comment by MohitMayankOP** [comment]
Hey @phurwicz, able to install using `conda install -c phurwicz hover`. For future reference, can we add it to readme? Thnx for the help!

**Comment by phurwicz** [comment]
Let me know if the conda installation above worked for you during runtime. I'm a bit concerned because the dependency specification for 0.5.0 on conda is flawed. I would delay adding conda installation to README till 0.6.0 makes it to conda-forge. (This should happen within a few weeks)

**Comment by MohitMayankOP** [comment]
I tried it out and it didn't. First I had to reinstall certain packages due to version conflicts, which is okay. But even after that when I try to run hover using following code, I cannot see the visualization. Code I used, 

```python
from hover.recipes import simple_annotator
from hover.recipes.stable import _simple_annotator
from bokeh.io import show, output_notebook

output_notebook()

interactive_plot = simple_annotator(dataset)
show(interactive_plot, notebook_url='https://localhost:8888')
``` 

Console output I get, 

```
🔵 SupervisableTextDataset: Initializing...
🔵 SupervisableTextDataset: Deduplicating...
🔵 SupervisableTextDataset: --subset raw rows: 19544 -> 19544.
🔵 SupervisableTextDataset: --subset train rows: 0 -> 0.
🔵 SupervisableTextDataset: --subset dev rows: 0 -> 0.
🔵 SupervisableTextDataset: --subset test rows: 0 -> 0.
🟢 SupervisableTextDataset: Set up label encoder/decoder with 0 classes.
🟢 SupervisableTextDataset: Population updater: latest population with 0 classes.
🟢 SupervisableTextDataset: SupervisableTextDataset: finished initialization.
100%|█████████████████████████████████████████████████████████| 19544/19544 [00:00<00:00, 568139.76it/s]
🔵 SupervisableTextDataset: Fit-transforming UMAP on 19544 samples...
OMP: Info #271: omp_set_nested routine deprecated, please use omp_set_max_active_levels instead.
🔵 SupervisableTextDataset: Transforming UMAP on 0 samples...
```

Not sure if this is bcoz of my dataset or something else. But yeah the dependency spec is kinda flawed and requires manual effort.

**Comment by phurwicz** [comment]
The console output seems ok. There is a numba warning, but everything else is expected.

However, this output cannot be from the code block you posted. It should be from something like 
```
dataset = SupervisableTextDataset.from_pandas(<your_dataframe>)
dataset.compute_2d_embedding(*args)
```

If you see neither an exception or the visualization, then this particular problem is not with installation or dependencies. What about removing `notebook_url='https://localhost:8888'`?

Also `_simple_annotator` is different from `simple_annotator`. The web tutorial had to use `_simple_annotator`, but it explained that in real usage one should choose `simple_annotator` (without the underscore prefix).

**Comment by phurwicz** [comment]
Hi @MohitMayankOP, the package is now available: https://github.com/conda-forge/hover-feedstock

`conda install -c conda-forge hover` should do it :)

Please let me know if it runs ok (it should now).
