### ISSUE TITLE
Feedback on Quickstart

### ISSUE THREAD

**Issue by epugh** [phurwicz/hover#27]
For the step "Ingredient 2 / 3: Embedding", I had to follow the instructions on space to download the model...   Maybe this is a case where "if you can't figure out how to get a spacy model, you shouldn't be using hover" ;-)  

> python -m spacy download en_core_web_md

Also, when running in NOTEBOOK MODE with Jupyter,

This command didn't work:

> show(interactive_plot, notebook_url='https://localhost:8888')

But I tried just 

> show(interactive_plot)

and had success, at least in showing the widgets right in the notebook....!  Now, I noticed that they don't quite fit, but that might be another issue.

**Comment by phurwicz** [comment]
Hi Eric, many thanks! I got too absorbed into making the in-browser quickstart work that I forgot about local environments.

----

> For the step "Ingredient 2 / 3: Embedding", I had to follow the instructions on space to download the model...

I should have put a dependency note there for folks running the code in local environment. In the Binder environment `spacy` and the model are installed, but locally they are not required by `hover`, thus causing the issue you found.

----

> This command didn't work:
>
> > show(interactive_plot, notebook_url='https://localhost:8888/')
>
> But I tried just
> 
> > show(interactive_plot)

Interesting. Some folks used to find it the other way around. Let me put both (one of them commented out) in the code block. 

----

> Now, I noticed that they don't quite fit, but that might be another issue.

Could you share like a screenshot?
