### ISSUE TITLE
QuickStart via Docker Container

### ISSUE THREAD

**Issue by GeorgePearse** [phurwicz/hover#29]
Feel like this could be made to be very easy to demo/test, if it were possible to run some of the core components (UI) as a docker image, and then the data was loaded via an API.

**Comment by phurwicz** [comment]
Binder basically does this. Have you checked out the [docs page](https://phurwicz.github.io/hover/pages/tutorial/t0-quickstart/)? It prepares an environment for you to run custom demos and tests.

With docker it seems a little bit difficult to add custom code for data handling. It’s certainly possible to add the docker option, but I want to figure out the best way to support your use case.

**Comment by GeorgePearse** [comment]
I was having trouble with the Binder set-up (may be a problem with my browser now that I think about), but did quickly realise that it would be very hard to do this well in a docker container. Thanks for your help and quick response.

**Comment by phurwicz** [comment]
Just to clarify, does the in-browser code work for you now? To be specific
- There is a kernel status widget on the top of the quickstart page. Does it behave normally?
- Are you able to run the code snippets in your browser?

**Comment by GeorgePearse** [comment]
![image](https://user-images.githubusercontent.com/47161914/173808124-c9659c37-6ef8-4607-ab4b-3557020a289d.png)

On the very quick start route I'm having no luck. I don't have any browser extensions.

**Comment by haochuanwei** [comment]
> I don't have any browser extensions.

You are not expected to need one. Also for most purposes you don't need to go directly to Binder -- doc pages are supposed to use Binder under the hood and let you deal with code just like in a Jupyter notebook.

Example from my browser:

### Binder initializing itself; note the status change
<img width="1096" alt="Screen Shot 2022-06-15 at 4 04 27 AM" src="https://user-images.githubusercontent.com/20132314/173812725-486a27c5-3334-4de6-bab9-9b1806f627b5.png">

<img width="1096" alt="Screen Shot 2022-06-15 at 4 04 39 AM" src="https://user-images.githubusercontent.com/20132314/173812730-42f78b3c-e3e9-401c-a5ea-a35a0d003917.png">

<img width="1096" alt="Screen Shot 2022-06-15 at 4 04 46 AM" src="https://user-images.githubusercontent.com/20132314/173812737-65d4fab8-bad4-4c89-a72e-df123545112a.png">

### Running code in the browser
<img width="1096" alt="Screen Shot 2022-06-15 at 4 04 58 AM" src="https://user-images.githubusercontent.com/20132314/173812745-8a7b9476-926b-48a9-b7b1-d08e0d6bd948.png">

**Comment by FarisHijazi** [comment]
Hello, I also agree with the need to have a generic pre-coded demo where people can start with as a hello-world and move on from there, especially one that runs the server

**Comment by haochuanwei** [comment]
Hi Faris,

There are pre-coded demos in phurwicz/hover-binder (https://github.com/phurwicz/hover-binder). Basically you click on the link of a demo, wait for loading, and get to an annotation interface immediately. Does that meet this need?

Best regards,
Haochuan
________________________________

**Comment by FarisHijazi** [comment]
I do have some feedback actually, 

It would be great if [these pages](https://phurwicz.github.io/hover/pages/tutorial/t0-quickstart/) with jupyter-like cells actually had a downloadable jupyter notebook file (.ipynb)

I do need to mention that I'm not a fan of binder and it has a bit of a learning curve, ideally this app should be deployable locally through a webserver, is that possible with binder?

I forgot to mention, but I'm thankful for the useful tool, it's just that it's hard to get started with

**Comment by haochuanwei** [comment]
About downloading notebooks: great point, we will add it. For now there will be just the code blocks, but we plan to include the walkthrough properly.

About hosting on a server: yes, you can host on any server in any Python environment (https://phurwicz.github.io/hover/pages/tutorial/t2-bokeh-app/). Binder is just for hosting demos that don’t require you to install anything.
________________________________

**Comment by phurwicz** [comment]
@FarisHijazi notebook download is now available. The notebook has code blocks (adapted for local usage, slightly different from the doc page) *and* walkthrough markdown. 

For example, the [quickstart notebook](https://github.com/phurwicz/hover/blob/main/docs/pipelines/generated/t0-quickstart.ipynb) is auto-generated from the source code behind the [quickstart doc page](https://phurwicz.github.io/hover/pages/tutorial/t0-quickstart/).

On each notebook-like doc page, we added a line pointing to the folder of notebooks.
![Screen Shot 2022-07-23 at 7 48 12 PM](https://user-images.githubusercontent.com/74003834/180630054-1faa5df6-e5ae-46ed-9ea7-d0ff71fd7907.png)

----

> ideally this app should be deployable locally through a webserver

Let us know if we can assist further on this part. Thanks!

**Comment by FarisHijazi** [comment]
that's awesome! will check it out and let you know if I face any difficulties. Let's aim to make this app super easy to start with, because it has a LOT of useful features and it would be a shame to see people leave because they're too lazy to get it to start

**Comment by robinsonkwame** [comment]
ftw, I also found it difficult to load hover on my own because I do not know Bokeh. However, I was able to start the server by replacing the Server related code, including the `binder_proxy_app` call and imports, with the following:

```
server = Server(
    {'/my-app': interactive_plot},
    port=5007,
    allow_websocket_origin=['*'],
    use_xheaders=True
)

server.start()
server.io_loop.add_callback(server.show, "/my-app")
server.io_loop.start() 
```

All that aside, wonderful work!

**Comment by haochuanwei** [comment]
Hi Kwame, thanks first of all!

Were you running hover locally? If so, you are right to disregard the binder stuff. Those are only needed when you run code directly in the browser using a binder kernel instead of a local one. Could you help provide a little more info if any of the below cases apply?

  *   if you were running in the browser but needed to replace the code, please let me know.
  *   if you found the `binder_proxy_app` call anywhere other than the tutorials webpage, please let me know.

Both of the above would be unintended, and we are happy to correct it at once.

________________________________

**Comment by robinsonkwame** [comment]
Nope, I was running on the command line [in a project that leverages this one. ](https://github.com/robinsonkwame/qca-analysis-pipeline/blob/main/app/app.py)

**Comment by haochuanwei** [comment]
I see, yes for command line you do need bokeh server :)

Best regards,
Haochuan
________________________________
