### ISSUE TITLE
bulk labeling selection should automatically update "view selection"

### ISSUE THREAD

**Issue by FarisHijazi** [phurwicz/hover#42]
Hi, I'm running the [quickstart0 code](https://github.com/phurwicz/hover/blob/main/docs/pipelines/generated/t0-quickstart.ipynb).

Current behavior: after every selection (using lasso tool or poly tool) I have to press the button "View selected" so I can update the table
Desired (new) behavior: I would like this button to not exist and it should automatically update every time the selection is updated (be it lasso or poly tool)

I'll be happy to dig in the code, if you direct me to a general direction of where to look, I'm not sure how easy it is to write a hook for the bokeh plot

**Comment by phurwicz** [comment]
Let's look at "hook A", which calls `self._store_selection()` ("callback A") whenever a new selection is made: https://github.com/phurwicz/hover/blob/602ba8a244266894ef821025dc0e618170b380b0/hover/core/explorer/base.py#L408-L411


Also "callback B", which refreshes the table when you click "View Selected" ("hook B"):
https://github.com/phurwicz/hover/blob/602ba8a244266894ef821025dc0e618170b380b0/hover/core/dataset.py#L452-L460

https://github.com/phurwicz/hover/blob/602ba8a244266894ef821025dc0e618170b380b0/hover/core/dataset.py#L488


Basically you are looking for "hook A to trigger callback B". This is feasible.

Caveat 1: as you can tell from the file names, hook A and callback B are with different classes of objects. The way these two classes (`SupervisableDataset` and `BokehBaseExplorer`, to be specific) interact should probably go here https://github.com/phurwicz/hover/blob/602ba8a244266894ef821025dc0e618170b380b0/hover/core/dataset.py#L438
with something like this:
```python
explorer.figure.on_event(SelectionGeometry, callback_view) 
```

Caveat 2: the `SelectionGeometry` event is already tied to a few hooks. You might have noticed [**filters** and how they can trigger automatically](https://github.com/phurwicz/hover/blob/main/docs/pipelines/generated/t5-finder-selection-filter.ipynb) after making a selection. We want the table to update after all the filters, or any other hooks that alter the selection. So it takes a bit of finesse to place the `explorer.figure.on_event(...)` line at the right place of the "queue of hooks".

**Comment by FarisHijazi** [comment]
I'll see if I have time after work to get on it

**Comment by haochuanwei** [comment]
It turned out a bit more complicated than I first thought. Every mechanism that changes the selection (which is more than “hook A”) needs to trigger “callback B”. Took me a while to get the ordering figured out, will write tests and push to a nightly branch. Main branch would need to wait for more tests — would you mind installing from nightly before that?

Best regards,
Haochuan
________________________________

**Comment by FarisHijazi** [comment]
Yes I don't mind installing the nightly branches, just let me know when
it's out

**Comment by phurwicz** [comment]
Hi @FarisHijazi , c3db709d1a42faf1120d3fd8dcfb1e12bc96fd77 has the latest update. Below the "View Selected" you will see a toggle like this:
<img width="708" alt="Screen Shot 2022-07-28 at 5 44 44 AM" src="https://user-images.githubusercontent.com/74003834/181508139-e21cdb7f-c6e1-4c28-9fba-8c6aed64d81a.png">

Turn it on and you will have auto-refresh. Note that any edits you made in the selection table without hitting "Update Row Values" will be lost.

We've tested it in the annotation interface. Will add some automated tests later on. Hope it helps!
