### ISSUE TITLE
Setting custom colors 

### ISSUE THREAD

**Issue by robinsonkwame** [phurwicz/hover#45]
The default gray for ABSTAIN labels is difficult to see on my screen. I wondered if there was an easy way to set custom color per label.

**Comment by haochuanwei** [comment]
On the recipe​ (i.e. simple_annotator​) level there currently isn’t. For ABSTAIN the light gray color is kind of the point — ABSTAIN is the unlabeled background upon which labeled colors are applied.

If you’d like a custom color palette, the best place to do it is probably a Recipe​ class. Let me give more thought to this.

Best regards,
Haochuan
________________________________
From: Kwame Porter Robinson ***@***.***>
Sent: Sunday, August 21, 2022 1:22:59 AM
To: phurwicz/hover ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [phurwicz/hover] Setting custom colors (Issue #45)


The default gray for ABSTAIN labels is difficult to see on my screen. I wondered if there was an easy way to set custom color per label.

**Comment by robinsonkwame** [comment]
Great, looking forward to it. I actually thought the Bokeh icon was a color wheel and clicked it to modify the current label color. 

As an aside, maybe a roadmap needs-help-issue, UI accessibility will be greatly enhanced if users are able to control color settings and defaults. For example, Bokeh put accessibility related concerns on their roadmap, https://github.com/bokeh/bokeh/issues/12259, and other products let you specify color settings, such as the commercial prodi.gy that has a crude bulk labeling script. Libraries like colorcet provide ready made perceptually accurate pallets for dense data visualizations (colorcet.holoviz.org) too. 


On Aug 20, 2022, at 9:36 PM, Harry Wei ***@***.***> wrote:

﻿
On the recipe​ (i.e. simple_annotator​) level there currently isn’t. For ABSTAIN the light gray color is kind of the point — ABSTAIN is the unlabeled background upon which labeled colors are applied. 

If you’d like a custom color palette, the best place to do it is probably a Recipe​ class. Let me give more thought to this. 

Best regards, 
Haochuan 
________________________________ 
From: Kwame Porter Robinson ***@***.***> 
Sent: Sunday, August 21, 2022 1:22:59 AM 
To: phurwicz/hover ***@***.***> 
Cc: Subscribed ***@***.***> 
Subject: [phurwicz/hover] Setting custom colors (Issue #45) 


The default gray for ABSTAIN labels is difficult to see on my screen. I wondered if there was an easy way to set custom color per label.

**Comment by phurwicz** [comment]
Hi @robinsonkwame, custom colors are now supported 🎉 
```
# enter the hex code that works best for you
hover.config['visual']['abstain_hexcolor'] = "#dcdcdc"
```

for more information, you can
```
hover.config.hint()
```
