### ISSUE TITLE
Enable tooltips in selection table

### ISSUE THREAD

**Issue by robinsonkwame** [phurwicz/hover#48]
In the selection table it can be difficult to evict data points when the entire text may be needed for labeling context. This especially true for meaning derived from long range dependence between phrases. Currently that table cuts off the text. Bokeh DataTable [depends on strongly SlickGrid](https://stackoverflow.com/a/44157382/3662899) that does not easily allow row height to be dynamic. So, instead, to get full labeling text, I suggest that the `text` column be set with a `tooltip` template, eg. add a [`HTMLTemplateFormatter` to "text"](https://github.com/phurwicz/hover/blob/602ba8a244266894ef821025dc0e618170b380b0/hover/core/local_config.py#L48-L49) with
```
    if feature_key == "text":
        feature_col_kwargs["formatter"] = HTMLTemplateFormatter(
            template="""<span href="#" data-toggle="tooltip" title="<%= value %>"><%= value %></span>"""
        )
```

and if the text is too long yet someone wants to inspect it w/o figuring which of the many points it is they can just hover over it.

**Comment by haochuanwei** [comment]
This is awesome, thanks!

The suggested code looks good, please feel free to make a PR into the nightly branch. I happen to need a couple of days before being able to make write code on desktop, but I can certainly approve on mobile now and test nightly later before merging into main.

Best regards,
Haochuan
________________________________
From: Kwame Porter Robinson ***@***.***>
Sent: Wednesday, August 24, 2022 2:05:29 AM
To: phurwicz/hover ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [phurwicz/hover] Enable tooltips in selection table (Issue #48)


In the selection table it can be difficult to evict data points when the entire text may be needed for labeling context. This especially true for meaning derived from long range dependence between phrases. Currently that table cuts off the text. Bokeh DataTable depends on strongly SlickGrid<https://stackoverflow.com/a/44157382/3662899> that does not easily allow row height to be dynamic. So, instead, to get full labeling text, I suggest that the text column be set with a tooltip template, eg. add a HTMLTemplateFormatter to "text"<https://github.com/phurwicz/hover/blob/602ba8a244266894ef821025dc0e618170b380b0/hover/core/local_config.py#L48-L49> with

    if feature_key == "text":
        feature_col_kwargs["formatter"] = HTMLTemplateFormatter(
            template="""<span href="#" data-toggle="tooltip" title="<%= value %>"><%= value %></span>"""
        )


and if the text is too long yet someone wants to inspect it w/o figuring which of the many points it is they can just hover over it.

**Comment by robinsonkwame** [comment]
[Done](https://github.com/phurwicz/hover/pull/49).

**Comment by phurwicz** [comment]
https://github.com/phurwicz/hover/pull/52
