### ISSUE TITLE
Associating non_feature data with feature_key

### ISSUE THREAD

**Issue by robinsonkwame** [phurwicz/hover#53]
There are often metadata associated with the feature data; for example, text comes from certain documents. After labeling the raw data it's often useful to merge the labels with the metadata for other data science tasks. For example, some sets of documents or locations might not contain a labels that you would otherwise expect them to. Or you want to aggregate counts by document or location.

Is there a way for [SuperisableTextDataset ](https://github.com/phurwicz/hover/blob/44acf61e2f23b164474306a3b1f84ab9ef31579f/hover/core/dataset.py) to include `non_feature` data? `non_feature` data could store this kind of metadata. The subset row order differs from the raw data frame so you can't just match indices.

**Comment by phurwicz** [comment]
Yes, the dataset can have any extra columns as long as their names don't conflict with the columns that `hover` uses. 
- Some [specific functionalities](https://github.com/phurwicz/hover/blob/44acf61e2f23b164474306a3b1f84ab9ef31579f/tests/core/explorer/local_helper.py#L9-L15) use "pred_label"/"pred_score".
- [the plotting utility](https://github.com/phurwicz/hover/blob/5b8fb17f50a3c36726d4665d1cf1253ba4d5f2f9/hover/core/explorer/local_config.py) uses "\_\_COLOR\_\_", "\_\_ALPHA\_\_", etc.

Most of the time you simply won't hit a conflict, just pass your full csv to `SupervisableTextDataset.from_pandas()`.
