### ISSUE TITLE
Use of semi-supervised fit step for Umap and ivis

### ISSUE THREAD

**Issue by clemgaut** [phurwicz/hover#61]
Hello,

Thank you so much for providing hover as an open source tool!

I was wondering if it would be possible to have the option to make a semi-supervised fit with umap or ivis.
Indeed, from what I understand, both umap and ivis are fit in an unsupervised way: only the embedding information is used in the fit step.
For data belonging to the train and dev sets (public sets from hover implementation), hover knows what class they belong to. As both umap and ivis support providing labels during the fit step (-1 if no label is known, to do semi-supervised fit), I was wondering if you considered adding the class information in the fit step?

**Comment by phurwicz** [comment]
Hi @clemgaut, thanks for using hover!

Semi-supervised fit should be do-able right now. The trick would be
- use one-hot vectors to represent the class information
- concatenate the one-hot vector to the vector you are currently using

For example, let's say you are using unsupervised fit with some vectorizer function:
```python
def vectorizer_unsupervised(feature):
    # vector = some_pretrained_model(feature)
    return vector
```

You can pre-compute a feature -> label lookup and do
```python
# assuming a dictionary called "lookup" that maps labelled data to integer label
# also assuming that you already know the number of classes for your classifier
# if not, just set NUM_CLASSES to be large enough to cover known classes
NUM_CLASSES = 3

def one_hot_encoding(feature, num_classes):
    arr = np.zeros(num_classes)
    label = lookup.get(feature, -1)
    if label >= 0:
        arr[label] = 1.0
    return arr

def vectorizer_semisupervised(feature):
    vec1 = vectorizer_unsupervised(feature)
    vec2 = one_hot_encoding(feature, NUM_CLASSES)
    return np.concatenate(vec1, vec2)
```

**Comment by clemgaut** [comment]
Thank you, for your answer, I will also look into using the predefined functions of umap and ivis for unsupervised learning. I might do a PR if I get something working eventually.
